train:
  checkpoint: /home/harry/storj/runs/nanodrz/1706191922/0007000.pt
  continue_from_checkpoint: false
  total_steps: 30_000
  max_lr: 1e-4

model:
  num_embs: 352
  audio_encode: dac-codes

data:
  silence_max: 1
  interrupt_max: 0
  num_speakers: 2
